version: '2'

services:
  svc-mitreidc:
    build: ./assets/docker
    container_name: svc-mitreidc
    restart: always
    volumes:
       - /vagrant/run/mitreid_data:/opt/tomcat/webapps
    ports:
       - "8080:8080"

  svc-postgres:
    image: postgres
    container_name: svc-postgres
#    volumes:
#      - /vagrant/run/postgres_data:/pgdata
    environment:
      POSTGRES_USER: oic
      POSTGRES_PASSWORD: oic
      POSTGRES_DB: oic
#      PGDATA: /pgdata


