alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias benchhd='time sh -c "dd if=/dev/zero of=ddfile bs=8k count=250000 && sync"; rm ddfile'
alias dc='docker-compose'
alias dcl='docker-compose logs'
alias dcrm='docker-compose rm'
alias dcsrm='docker-compose stop && docker-compose rm'
alias dcs='docker-compose stop'
alias dcu='docker-compose up -d'
alias dcul='docker-compose up -d && docker-compose logs'
alias dpl='docker logs'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias drm='docker rm'
alias drmi='docker rmi'
alias egrep='egrep --color=auto'
alias emc='emacs'
alias ep='emacs ~/.profile'
alias fgrep='fgrep --color=auto'
alias frontexex='docker exec -ti frontend_nginxgen_1 /bin/bash'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias ransack='ransack'
alias sp='source ~/.profile'
alias sudo='sudo '
alias ta='tmux attach'
alias vhosts='cat /var/lib/bind/db.canamaque.com | grep 151.80.42.214 | awk '\''{print $1}'\'''
alias yt-downloader='youtubeDownloaderFn'

#--- Vagrant
alias vstatus='vagrant global-status'
alias vssh='vagrant ssh'
alias vdf='vagrant destroy -f'
alias vss='vagrant snapshot save '
alias vsr='vagrant snapshot restore '
alias vsl='vagrant snapshot list'
alias vsd='vagrant snapshot delete'
